target 'Basic' do
  pod 'React', subspecs: [
    'RCTAnimation',
    'RCTPushNotification',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport',
  ], path: '../node_modules/react-native'

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'react-native-keyframes',  path: '../node_modules/@ptomasroos/react-native-keyframes/'
  pod 'keyframes', :git => 'https://github.com/ptomasroos/Keyframes.git', :commit => '3f0be2850fed20ad2f0c3db987ec6be846f3177c'
end
