target 'Keyframes' do
  pod 'React', path: '../node_modules/react-native'
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'keyframes', :git => 'https://github.com/ptomasroos/Keyframes.git', :commit => '3f0be2850fed20ad2f0c3db987ec6be846f3177c'
end
